// موسّع: جميع دول العالم مع الولايات/المناطق والمدن الرئيسية + قائمة اللغات العالمية المعتمدة
import regionsData from "./regions.data.json";
export const WORLD_REGIONS: Record<string, { states: Record<string, string[]> }> = regionsData as Record<
  string,
  { states: Record<string, string[]> }
>;
export const COUNTRIES = Object.keys(WORLD_REGIONS);

// قائمة اللغات العالمية المعتمدة (184 لغة) — للاختيار في الإعدادات والمنطقة
export const WORLD_LANGUAGES: Record<string, { nameAr: string; nameEn: string }> = {
  ar: { nameAr: "العربية", nameEn: "Arabic" },
  zh: { nameAr: "الصينية", nameEn: "Chinese" },
  en: { nameAr: "الإنجليزية", nameEn: "English" },
  hi: { nameAr: "الهندية", nameEn: "Hindi" },
  es: { nameAr: "الإسبانية", nameEn: "Spanish" },
  fr: { nameAr: "الفرنسية", nameEn: "French" },
  bn: { nameAr: "البنغالية", nameEn: "Bengali" },
  pt: { nameAr: "البرتغالية", nameEn: "Portuguese" },
  ru: { nameAr: "الروسية", nameEn: "Russian" },
  ur: { nameAr: "الأردية", nameEn: "Urdu" },
  id: { nameAr: "الإندونيسية", nameEn: "Indonesian" },
  de: { nameAr: "الألمانية", nameEn: "German" },
  ja: { nameAr: "اليابانية", nameEn: "Japanese" },
  sw: { nameAr: "السواحيلية", nameEn: "Swahili" },
  mr: { nameAr: "الماراثية", nameEn: "Marathi" },
  te: { nameAr: "التيلوغوية", nameEn: "Telugu" },
  tr: { nameAr: "التركية", nameEn: "Turkish" },
  ta: { nameAr: "التاميلية", nameEn: "Tamil" },
  vi: { nameAr: "الفيتنامية", nameEn: "Vietnamese" },
  it: { nameAr: "الإيطالية", nameEn: "Italian" },
  ko: { nameAr: "الكورية", nameEn: "Korean" },
  fa: { nameAr: "الفارسية", nameEn: "Persian" },
  pl: { nameAr: "البولندية", nameEn: "Polish" },
  uk: { nameAr: "الأوكرانية", nameEn: "Ukrainian" },
  nl: { nameAr: "الهولندية", nameEn: "Dutch" },
  th: { nameAr: "التايلاندية", nameEn: "Thai" },
  gu: { nameAr: "الغوجاراتية", nameEn: "Gujarati" },
  my: { nameAr: "البورمية", nameEn: "Burmese" },
  ro: { nameAr: "الرومانية", nameEn: "Romanian" },
  ps: { nameAr: "البشتوية", nameEn: "Pashto" },
  ha: { nameAr: "الهوسا", nameEn: "Hausa" },
  el: { nameAr: "اليونانية", nameEn: "Greek" },
  cs: { nameAr: "التشيكية", nameEn: "Czech" },
  sv: { nameAr: "السويدية", nameEn: "Swedish" },
  hu: { nameAr: "المجرية", nameEn: "Hungarian" },
  he: { nameAr: "العبرية", nameEn: "Hebrew" },
  da: { nameAr: "الدنماركية", nameEn: "Danish" },
  fi: { nameAr: "الفنلندية", nameEn: "Finnish" },
  sk: { nameAr: "السلوفاكية", nameEn: "Slovak" },
  no: { nameAr: "النرويجية", nameEn: "Norwegian" },
  ms: { nameAr: "الماليزية", nameEn: "Malay" },
  am: { nameAr: "الأمهرية", nameEn: "Amharic" },
  bg: { nameAr: "البلغارية", nameEn: "Bulgarian" },
  yo: { nameAr: "اليوروبا", nameEn: "Yoruba" },
  or: { nameAr: "الأوريا", nameEn: "Odia" },
  sr: { nameAr: "الصربية", nameEn: "Serbian" },
  hr: { nameAr: "الكرواتية", nameEn: "Croatian" },
  be: { nameAr: "البيلاروسية", nameEn: "Belarusian" },
  ka: { nameAr: "الجورجية", nameEn: "Georgian" },
  pa: { nameAr: "البنجابية", nameEn: "Punjabi" },
  kn: { nameAr: "الكانادا", nameEn: "Kannada" },
  ml: { nameAr: "المالايالامية", nameEn: "Malayalam" },
  sd: { nameAr: "السندية", nameEn: "Sindhi" },
  si: { nameAr: "السنهالية", nameEn: "Sinhala" },
  ne: { nameAr: "النيبالية", nameEn: "Nepali" },
  km: { nameAr: "الخميرية", nameEn: "Khmer" },
  kk: { nameAr: "الكازاخية", nameEn: "Kazakh" },
  az: { nameAr: "الأذربيجانية", nameEn: "Azerbaijani" },
  uz: { nameAr: "الأوزبكية", nameEn: "Uzbek" },
  tg: { nameAr: "الطاجيكية", nameEn: "Tajik" },
  lt: { nameAr: "الليتوانية", nameEn: "Lithuanian" },
  lv: { nameAr: "اللاتفية", nameEn: "Latvian" },
  et: { nameAr: "الإستونية", nameEn: "Estonian" },
  mk: { nameAr: "المقدونية", nameEn: "Macedonian" },
  sq: { nameAr: "الألبانية", nameEn: "Albanian" },
  sl: { nameAr: "السلوفينية", nameEn: "Slovenian" },
  mt: { nameAr: "المالطية", nameEn: "Maltese" },
  ga: { nameAr: "الأيرلندية", nameEn: "Irish" },
  cy: { nameAr: "الويلزية", nameEn: "Welsh" },
  is: { nameAr: "الأيسلندية", nameEn: "Icelandic" },
  hy: { nameAr: "الأرمينية", nameEn: "Armenian" },
  eu: { nameAr: "الباسكية", nameEn: "Basque" },
  ca: { nameAr: "الكتالانية", nameEn: "Catalan" },
  gl: { nameAr: "الجاليكية", nameEn: "Galician" },
  gd: { nameAr: "الغيلية الاسكتلندية", nameEn: "Scottish Gaelic" },
  lb: { nameAr: "اللوكسمبرغية", nameEn: "Luxembourgish" },
  af: { nameAr: "الأفريقانية", nameEn: "Afrikaans" },
  zu: { nameAr: "الزولو", nameEn: "Zulu" },
  xh: { nameAr: "الخوسا", nameEn: "Xhosa" },
  ig: { nameAr: "الإيغبو", nameEn: "Igbo" },
  sn: { nameAr: "الشونا", nameEn: "Shona" },
  mg: { nameAr: "الملغاشية", nameEn: "Malagasy" },
  so: { nameAr: "الصومالية", nameEn: "Somali" },
  ti: { nameAr: "التغرينية", nameEn: "Tigrinya" },
  om: { nameAr: "الأورومية", nameEn: "Oromo" },
  wo: { nameAr: "الولوفية", nameEn: "Wolof" },
  bm: { nameAr: "البمبرية", nameEn: "Bambara" },
  ff: { nameAr: "الفولانية", nameEn: "Fulfulde" },
  ki: { nameAr: "الكيكويو", nameEn: "Kikuyu" },
  lg: { nameAr: "اللوغاندا", nameEn: "Luganda" },
  ny: { nameAr: "الشيشيوا", nameEn: "Chichewa" },
  st: { nameAr: "السوتو", nameEn: "Sesotho" },
  tn: { nameAr: "التسوانية", nameEn: "Setswana" },
  nso: { nameAr: "السوثو الشمالية", nameEn: "Northern Sotho" },
  ss: { nameAr: "السوازي", nameEn: "Swati" },
  ts: { nameAr: "التسونغا", nameEn: "Tsonga" },
  ve: { nameAr: "الفيندا", nameEn: "Venda" },
  nr: { nameAr: "النديبيل", nameEn: "Ndebele" },
  ku: { nameAr: "الكردية", nameEn: "Kurdish" },
  bo: { nameAr: "التبتية", nameEn: "Tibetan" },
  dz: { nameAr: "الدزونخا", nameEn: "Dzongkha" },
  mn: { nameAr: "المغولية", nameEn: "Mongolian" },
  ky: { nameAr: "القيرغيزية", nameEn: "Kyrgyz" },
  tk: { nameAr: "التركمانية", nameEn: "Turkmen" },
  tt: { nameAr: "التتارية", nameEn: "Tatar" },
  ba: { nameAr: "الباشكيرية", nameEn: "Bashkir" },
  cv: { nameAr: "التشوفاشية", nameEn: "Chuvash" },
  ce: { nameAr: "الشيشانية", nameEn: "Chechen" },
  sah: { nameAr: "الياقوتية", nameEn: "Yakut" },
  ug: { nameAr: "الأويغورية", nameEn: "Uyghur" },
  lo: { nameAr: "اللاوية", nameEn: "Lao" },
  tl: { nameAr: "التاغالوغية", nameEn: "Tagalog" },
  ceb: { nameAr: "السيبوانية", nameEn: "Cebuano" },
  hil: { nameAr: "الهيليغينونية", nameEn: "Hiligaynon" },
  war: { nameAr: "الواراي", nameEn: "Waray" },
  pag: { nameAr: "البانغاسينانية", nameEn: "Pangasinan" },
  jv: { nameAr: "الجاوية", nameEn: "Javanese" },
  su: { nameAr: "السوندانية", nameEn: "Sundanese" },
  mad: { nameAr: "المادورية", nameEn: "Madurese" },
  min: { nameAr: "المينانغكاباو", nameEn: "Minangkabau" },
  bjn: { nameAr: "البانجارية", nameEn: "Banjar" },
  ace: { nameAr: "الأتشينية", nameEn: "Acehnese" },
  bal: { nameAr: "البلوشية", nameEn: "Balochi" },
  mzn: { nameAr: "الطبرية", nameEn: "Mazandarani" },
  gil: { nameAr: "الغيلانية", nameEn: "Gilaki" },
  lrc: { nameAr: "اللورية الشمالية", nameEn: "Northern Luri" },
  ckb: { nameAr: "الكردية السورانية", nameEn: "Sorani Kurdish" },
  kmr: { nameAr: "الكردية الكرمانجية", nameEn: "Kurmanji Kurdish" },
  zh_yue: { nameAr: "الكانتونية", nameEn: "Cantonese" },
  wuu: { nameAr: "الوو", nameEn: "Wu Chinese" },
  nan: { nameAr: "المين نان", nameEn: "Southern Min" },
  yue: { nameAr: "اليوي", nameEn: "Yue Chinese" },
  hak: { nameAr: "الهاكا", nameEn: "Hakka" },
  gan: { nameAr: "الغان", nameEn: "Gan Chinese" },
  xiang: { nameAr: "الشيانغ", nameEn: "Xiang Chinese" },
  hmn: { nameAr: "الهمونغ", nameEn: "Hmong" },
  ii: { nameAr: "اليي", nameEn: "Yi" },
  za: { nameAr: "الزوانغ", nameEn: "Zhuang" },
  knc: { nameAr: "الكانوري", nameEn: "Kanuri" },
  tiv: { nameAr: "التيف", nameEn: "Tiv" },
  ksw: { nameAr: "الكارين", nameEn: "Karen" },
  shan: { nameAr: "الشانية", nameEn: "Shan" },
  chr: { nameAr: "التشيروكية", nameEn: "Cherokee" },
  nv: { nameAr: "النافاجو", nameEn: "Navajo" },
  qu: { nameAr: "الكيتشوا", nameEn: "Quechua" },
  ay: { nameAr: "الأيمارا", nameEn: "Aymara" },
  gn: { nameAr: "الغوارانية", nameEn: "Guarani" },
  ht: { nameAr: "الكريولية الهايتية", nameEn: "Haitian Creole" },
  cre: { nameAr: "الكريولية الفرنسية", nameEn: "French Creole" },
  pcm: { nameAr: "البيدجين النيجيرية", nameEn: "Nigerian Pidgin" },
  aa: { nameAr: "العفرية", nameEn: "Afar" },
  ab: { nameAr: "الأبخازية", nameEn: "Abkhazian" },
  ae: { nameAr: "الأفستية", nameEn: "Avestan" },
  ak: { nameAr: "الأكانية", nameEn: "Akan" },
  an: { nameAr: "الأراغونية", nameEn: "Aragonese" },
  av: { nameAr: "الأوارية", nameEn: "Avaric" },
  bi: { nameAr: "البيسلامية", nameEn: "Bislama" },
  br: { nameAr: "البريتونية", nameEn: "Breton" },
  bs: { nameAr: "البوسنية", nameEn: "Bosnian" },
  co: { nameAr: "الكورسية", nameEn: "Corsican" },
  cr: { nameAr: "الكري", nameEn: "Cree" },
  dv: { nameAr: "الديفهية", nameEn: "Divehi" },
  ee: { nameAr: "الإيوي", nameEn: "Ewe" },
  eo: { nameAr: "الإسبرانتو", nameEn: "Esperanto" },
  fj: { nameAr: "الفيجية", nameEn: "Fijian" },
  fo: { nameAr: "الفاروية", nameEn: "Faroese" },
  fy: { nameAr: "الفريزية الغربية", nameEn: "Western Frisian" },
  gv: { nameAr: "المانكسية", nameEn: "Manx" },
  ho: { nameAr: "الهيري موتو", nameEn: "Hiri Motu" },
  io: { nameAr: "الإيدو", nameEn: "Ido" },
  kg: { nameAr: "الكونغوية", nameEn: "Kongo" },
  la: { nameAr: "اللاتينية", nameEn: "Latin" },
  li: { nameAr: "الليمبورغية", nameEn: "Limburgish" },
  ln: { nameAr: "اللينغالا", nameEn: "Lingala" },
  lu: { nameAr: "اللوبا كاتانغا", nameEn: "Luba-Katanga" },
  mh: { nameAr: "المارشالية", nameEn: "Marshallese" },
  na: { nameAr: "الناوروية", nameEn: "Nauru" },
  nb: { nameAr: "النرويجية بوكمال", nameEn: "Norwegian Bokmål" },
  nd: { nameAr: "النديبيلية الشمالية", nameEn: "North Ndebele" },
  ng: { nameAr: "الندونغية", nameEn: "Ndonga" },
  oc: { nameAr: "الأوكسيتانية", nameEn: "Occitan" },
  oj: { nameAr: "الأوجيبوية", nameEn: "Ojibwa" },
  os: { nameAr: "الأوسيتية", nameEn: "Ossetian" },
  pi: { nameAr: "البالية", nameEn: "Pali" },
  rm: { nameAr: "الرومانشية", nameEn: "Romansh" },
  rn: { nameAr: "الروندية", nameEn: "Rundi" },
  rw: { nameAr: "الكينيارواندا", nameEn: "Kinyarwanda" },
  sa: { nameAr: "السنسكريتية", nameEn: "Sanskrit" },
  sc: { nameAr: "السردينية", nameEn: "Sardinian" },
  sg: { nameAr: "السانغوية", nameEn: "Sango" },
  sm: { nameAr: "الساموية", nameEn: "Samoan" },
  to: { nameAr: "التونغية", nameEn: "Tonga" },
  tw: { nameAr: "التوي", nameEn: "Twi" },
  ty: { nameAr: "التاهيتية", nameEn: "Tahitian" },
  vo: { nameAr: "الفولابوك", nameEn: "Volapük" },
  wa: { nameAr: "الوالونية", nameEn: "Walloon" },
};
