import { PlatformShell } from "@/components/PlatformShell";
import { trpc } from "@/lib/trpc";
import { Check, Clock3, UserPlus, X } from "lucide-react";
import { useLanguage } from "@/lib/i18n";
import { useLocation } from "wouter";
import { toast } from "sonner";

function PersonCard({ user, children, subtitle }: { user: any; children: React.ReactNode; subtitle: string }) {
  const [, setLocation] = useLocation();
  return <article className="flex flex-wrap items-center justify-between gap-4 rounded-2xl border border-white/10 bg-black/15 p-4"><button type="button" onClick={() => setLocation(`/profile/${user.id}`)} className="flex min-w-0 items-center gap-3 text-start"><div className="grid h-12 w-12 shrink-0 place-items-center overflow-hidden rounded-2xl bg-gradient-to-br from-violet-500 to-pink-500 font-bold">{user.avatarUrl ? <img src={user.avatarUrl} alt="" className="h-full w-full object-cover"/> : (user.name?.[0] || user.username?.[0] || "V")}</div><span className="min-w-0"><b className="block truncate">{user.name || user.username || "مستخدم VibraCam"}</b><small className="block truncate text-violet-100/55">@{user.username || "vibracam"} · {subtitle}</small></span></button><div className="flex flex-wrap gap-2">{children}</div></article>;
}

export default function FriendRequests() {
  const { t } = useLanguage();
  const [, setLocation] = useLocation();
  const utils = trpc.useUtils();
  const incoming = trpc.friendRequests.incoming.useQuery();
  const outgoing = trpc.friendRequests.outgoing.useQuery();
  const refresh = () => { void utils.friendRequests.incoming.invalidate(); void utils.friendRequests.outgoing.invalidate(); void utils.notifications.list.invalidate(); };
  const accept = trpc.friendRequests.accept.useMutation({ onSuccess: () => { toast.success(t("تم قبول طلب الصداقة.")); refresh(); }, onError: error => toast.error(error.message) });
  const reject = trpc.friendRequests.reject.useMutation({ onSuccess: () => { toast.success(t("تم رفض طلب الصداقة.")); refresh(); }, onError: error => toast.error(error.message) });
  const cancel = trpc.friendRequests.cancel.useMutation({ onSuccess: () => { toast.success(t("تم إلغاء طلب الصداقة.")); refresh(); }, onError: error => toast.error(error.message) });
  return <PlatformShell><div className="mx-auto max-w-4xl space-y-6"><header className="rounded-3xl glass p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm text-pink-200">VibraCam</p><h1 className="mt-1 flex items-center gap-2 text-3xl font-extrabold"><UserPlus size={27}/>{t("طلبات الصداقة")}</h1><p className="mt-2 leading-7 text-violet-100/65">{t("أرسل طلبات الصداقة وتابع الطلبات الواردة، ولا تصبح الصداقة متبادلة إلا بعد موافقة الطرف الآخر.")}</p></div><button type="button" onClick={() => setLocation("/discover")} className="rounded-xl px-4 py-2 gradient-button">{t("اكتشاف أشخاص")}</button></div></header><section className="rounded-3xl glass p-5"><h2 className="flex items-center gap-2 text-xl font-bold"><Clock3 size={19} className="text-pink-200"/>{t("الطلبات الواردة")} <span className="rounded-full bg-pink-500/20 px-2 py-0.5 text-xs">{incoming.data?.length ?? 0}</span></h2><div className="mt-4 space-y-3">{incoming.isLoading && <p className="text-sm text-violet-100/55">{t("جارٍ تحميل الطلبات...")}</p>}{incoming.data?.map(item => <PersonCard key={item.request.id} user={item.user} subtitle={t("طلب صداقة") }><button type="button" onClick={() => accept.mutate({ requestId: item.request.id })} disabled={accept.isPending} className="inline-flex items-center gap-1 rounded-xl px-3 py-2 text-sm gradient-button disabled:opacity-50"><Check size={15}/>{t("قبول")}</button><button type="button" onClick={() => reject.mutate({ requestId: item.request.id })} disabled={reject.isPending} className="inline-flex items-center gap-1 rounded-xl px-3 py-2 text-sm soft-button disabled:opacity-50"><X size={15}/>{t("رفض")}</button></PersonCard>)}{!incoming.isLoading && !incoming.data?.length && <p className="rounded-2xl border border-dashed border-white/10 p-8 text-center text-sm text-violet-100/55">{t("لا توجد طلبات صداقة واردة الآن.")}</p>}</div></section><section className="rounded-3xl glass p-5"><h2 className="flex items-center gap-2 text-xl font-bold"><UserPlus size={19} className="text-pink-200"/>{t("الطلبات الصادرة")} <span className="rounded-full bg-violet-500/20 px-2 py-0.5 text-xs">{outgoing.data?.length ?? 0}</span></h2><div className="mt-4 space-y-3">{outgoing.isLoading && <p className="text-sm text-violet-100/55">{t("جارٍ تحميل الطلبات...")}</p>}{outgoing.data?.map(item => <PersonCard key={item.request.id} user={item.user} subtitle={t("بانتظار الرد") }><button type="button" onClick={() => cancel.mutate({ requestId: item.request.id })} disabled={cancel.isPending} className="inline-flex items-center gap-1 rounded-xl px-3 py-2 text-sm soft-button disabled:opacity-50"><X size={15}/>{t("إلغاء الطلب")}</button></PersonCard>)}{!outgoing.isLoading && !outgoing.data?.length && <p className="rounded-2xl border border-dashed border-white/10 p-8 text-center text-sm text-violet-100/55">{t("لا توجد طلبات صداقة صادرة الآن.")}</p>}</div></section></div></PlatformShell>;
}
