import { PlatformShell } from "@/components/PlatformShell";
import { trpc } from "@/lib/trpc";
import { Laptop, LoaderCircle, LogOut, ShieldCheck } from "lucide-react";
import { toast } from "sonner";
import { useLanguage } from "@/lib/i18n";

export default function SecuritySessions() {
  const { t } = useLanguage();
  const utils = trpc.useUtils();
  const sessions = trpc.auth.sessions.useQuery();
  const revoke = trpc.auth.revokeSession.useMutation({ onSuccess: async () => { await utils.auth.sessions.invalidate(); toast.success("تم إنهاء الجلسة."); }, onError: error => toast.error(error.message) });
  const revokeOthers = trpc.auth.revokeOtherSessions.useMutation({ onSuccess: async () => { await utils.auth.sessions.invalidate(); toast.success("تم إنهاء جميع الجلسات الأخرى."); }, onError: error => toast.error(error.message) });
  return <PlatformShell><div className="mx-auto max-w-3xl"><p className="text-sm text-pink-200">{t('الحساب')}</p><h1 className="mt-1 text-3xl font-extrabold">{t('الأجهزةوالجلسات')}</h1><p className="mt-2 leading-7 text-violet-100/65">{t('راجعالأجهزةالتيدخلتبحسابكالمحلي')}</p><section className="mt-6 rounded-3xl glass p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-2"><ShieldCheck className="text-pink-300" size={22}/><h2 className="font-bold">{t('الجلساتالنشطة')}</h2></div><button disabled={revokeOthers.isPending} onClick={() => revokeOthers.mutate()} className="inline-flex items-center gap-2 rounded-xl px-4 py-2 text-sm soft-button disabled:opacity-50"><LogOut size={16}/>{t('إنهاءالجلساتالأخرى')}</button></div><div className="mt-5 space-y-3">{sessions.isLoading && <LoaderCircle className="mx-auto my-8 animate-spin text-pink-300"/>}{sessions.data?.map(session => <article key={session.id} className="flex flex-wrap items-center justify-between gap-4 rounded-2xl border border-white/10 bg-black/15 p-4"><div className="flex min-w-0 items-start gap-3"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-pink-500/15 text-pink-200"><Laptop size={18}/></div><span className="min-w-0"><b className="flex items-center gap-2">{session.current ? "هذا الجهاز" : "جهاز نشط"}{session.current && <small className="rounded-full bg-emerald-400/15 px-2 py-0.5 text-[10px] text-emerald-200">{t('الحالي')}</small>}</b><small className="mt-1 block break-words text-violet-100/50">{session.userAgent || "متصفح غير معروف"}</small><small className="mt-1 block text-violet-100/40">آخر نشاط: {new Date(session.lastActiveAt).toLocaleString("ar-SA")}</small></span></div>{!session.current && <button disabled={revoke.isPending} onClick={() => revoke.mutate({ sessionId: session.id })} className="rounded-xl px-3 py-2 text-sm text-rose-100 soft-button">{t('إنهاءالجلسة')}</button>}</article>)}{!sessions.isLoading && !sessions.data?.length && <p className="rounded-2xl border border-dashed border-white/15 p-8 text-center text-sm text-violet-100/55">{t('لاتوجدجلساتمحليةنشطةبعد')}</p>}</div></section></div></PlatformShell>;
}
