import { MediaUploader, type UploadedMedia } from "@/components/MediaUploader";
import { PlatformShell } from "@/components/PlatformShell";
import { trpc } from "@/lib/trpc";
import { Plus, Timer } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import { useLanguage } from "@/lib/i18n";

export default function Stories() {
  const { t } = useLanguage();
  const stories = trpc.stories.list.useQuery();
  const utils = trpc.useUtils();
  const [media, setMedia] = useState<UploadedMedia | null>(null);
  const [caption, setCaption] = useState("");
  const create = trpc.stories.create.useMutation({ onSuccess: () => { setMedia(null); setCaption(""); utils.stories.list.invalidate(); toast.success("نُشرت قصتك لمدة 24 ساعة."); } });
  return <PlatformShell><div className="mx-auto max-w-5xl"><p className="text-sm text-pink-200">{t('لحظاتسريعة')}</p><h1 className="mt-1 text-3xl font-extrabold">{t('القصص')}</h1><section className="mt-6 rounded-3xl glass p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-bold">{t('أضفقصتك')}</h2><p className="mt-1 text-sm text-violet-100/60">{t('تختفيتلقائيابعد24ساعة')}</p></div><MediaUploader kind="story" accept="image/*,video/*" onUploaded={setMedia} label={t("رفعصورةأوفيديو")}/></div>{media && <div className="mt-4 grid gap-3 sm:grid-cols-[200px_1fr]"><div className="overflow-hidden rounded-2xl bg-black/30">{media.type === "video" ? <video src={media.url} controls className="h-48 w-full object-cover"/> : <img src={media.url} alt="" className="h-48 w-full object-cover"/>}</div><div><textarea value={caption} onChange={event => setCaption(event.target.value)} placeholder={t("أضفوصفااختياريا")} rows={3} className="w-full rounded-xl border border-white/10 bg-black/20 p-3 outline-none focus:border-pink-300/60"/><button onClick={() => create.mutate({ mediaUrl: media.url, mediaKey: media.key, mediaType: media.type === "video" ? "video" : "image", caption: caption || null })} className="mt-3 inline-flex items-center gap-2 rounded-xl px-4 py-2 gradient-button"><Plus size={17}/>{t('نشرالقصة')}</button></div></div>}</section><section className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{stories.data?.map(({ story, author }) => <article key={story.id} className="relative overflow-hidden rounded-3xl border border-white/10 bg-black/20"><div className="aspect-[4/5]">{story.mediaType === "video" ? <video src={story.mediaUrl} controls className="h-full w-full object-cover"/> : <img src={story.mediaUrl} alt={t("قصة")} className="h-full w-full object-cover"/>}</div><div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-black/85 to-transparent p-4"><div className="flex items-center gap-2 mb-2"><div className="grid h-8 w-8 place-items-center overflow-hidden rounded-full bg-gradient-to-br from-violet-500 to-pink-500 font-bold text-white text-xs">{author.avatarUrl ? <img src={author.avatarUrl} alt="" className="h-full w-full object-cover" onError={(e) => { e.currentTarget.style.display = 'none'; e.currentTarget.parentElement!.innerText = author.name?.[0]?.toUpperCase() || "V"; }}/> : (author.name?.[0]?.toUpperCase() || "V")}</div><b>{author.name || "مستخدم VibraCam"}</b></div>{story.caption && <p className="mt-1 text-sm">{story.caption}</p>}<small className="mt-2 flex items-center gap-1 text-white/65"><Timer size={13}/>{t('تختفيخلال24ساعة')}</small></div></article>)}{!stories.data?.length && <div className="col-span-full rounded-3xl border border-dashed border-white/15 p-10 text-center text-violet-100/60">{t('لاتوجدقصصنشطةالآن')}</div>}</section></div></PlatformShell>;
}
